sensors:
- id: curr1
  type: current
  sampling_rate: 1
  signal:
    model: current
    params:
      base: 1
      fundamental: 2.5
      freq: 50
      thd3_amp: 0.15
      thd3_phase: 0.1
      thd5_amp: 0.05
      thd5_phase: 0.2
      load_period: 10
      delta_i: 1
      tau_load: 1
  noise:
    model: gaussian
    params:
      sigma: 0.05
  fault:
    model: none
    params: {}
- id: curr2
  type: current
  sampling_rate: 1
  signal:
    model: current
    params:
      base: 1
      fundamental: 2.5
      freq: 50
      thd3_amp: 0.15
      thd3_phase: 0.1
      thd5_amp: 0.05
      thd5_phase: 0.2
      load_period: 10
      delta_i: 1
      tau_load: 1
  noise:
    model: gaussian
    params:
      sigma: 0.01
  fault:
    model: none
    params: {}
- id: curr3
  type: current
  sampling_rate: 1
  signal:
    model: current
    params:
      base: 1
      fundamental: 2.5
      freq: 50
      thd3_amp: 0.15
      thd3_phase: 0.1
      thd5_amp: 0.05
      thd5_phase: 0.2
      load_period: 10
      delta_i: 1
      tau_load: 1
  noise:
    model: pink
    params:
      sigma: 0.03
  fault:
    model: none
    params: {}
- id: curr4
  type: current
  sampling_rate: 1
  signal:
    model: current
    params:
      base: 1
      fundamental: 2.5
      freq: 50
      thd3_amp: 0.15
      thd3_phase: 0.1
      thd5_amp: 0.05
      thd5_phase: 0.2
      load_period: 10
      delta_i: 1
      tau_load: 1
  noise:
    model: pink
    params:
      sigma: 0.03
  fault:
    model: spike
    params:
      probability: 0.01
      magnitude: 1
simulation:
  duration_seconds: 30
  output_csv: ../../output/sensor_data.csv
  seed: 4
